# Random Forest Vs Decision Tree UK Accident Data 2012-2014

### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Get The Data

In [2]:
df = pd.read_csv('accidents_2012_to_2014.csv')
df.head()

C:\Users\etallen127\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Accident_Index  Location_Easting_OSGR  Location_Northing_OSGR  Longitude  \
0  201201BS70001                 527200                  178760  -0.169101   
1  201201BS70002                 524930                  181430  -0.200838   
2  201201BS70003                 525860                  178080  -0.188636   
3  201201BS70004                 524980                  181030  -0.200259   
4  201201BS70005                 526170                  179200  -0.183773   

    Latitude  Police_Force  Accident_Severity  Number_of_Vehicles  \
0  51.493429             1                  3                   2   
1  51.517931             1                  3                   2   
2  51.487618             1                  3                   2   
3  51.514325             1                  3                   1   
4  51.497614             1                  3                   1   

   Number_of_Casualties        Date  ...   \
0                     1  19/01/2012  ...    
1                     1  04/01/2012  ...    
2                     1  10/01/2012  ...    
3                     1  18/01/2012  ...    
4                     1  17/01/2012  ...    

       Pedestrian_Crossing-Physical_Facilities  \
0  Pedestrian phase at traffic signal junction   
1        No physical crossing within 50 meters   
2             non-junction pedestrian crossing   
3        No physical crossing within 50 meters   
4        No physical crossing within 50 meters   

                          Light_Conditions       Weather_Conditions  \
0  Darkness: Street lights present and lit  Fine without high winds   
1  Darkness: Street lights present and lit  Fine without high winds   
2           Daylight: Street light present  Fine without high winds   
3           Daylight: Street light present  Fine without high winds   
4  Darkness: Street lights present and lit  Fine without high winds   

  Road_Surface_Conditions  Special_Conditions_at_Site  Carriageway_Hazards  \
0                     Dry                        None                 None   
1                     Dry                        None                 None   
2                     Dry                        None                 None   
3                     Dry                        None                 None   
4                     Dry                        None                 None   

  Urban_or_Rural_Area  Did_Police_Officer_Attend_Scene_of_Accident  \
0                   1                                          Yes   
1                   1                                          Yes   
2                   1                                          Yes   
3                   1                                          Yes   
4                   1                                          Yes   

   LSOA_of_Accident_Location  Year  
0                  E01002821  2012  
1                  E01004760  2012  
2                  E01002893  2012  
3                  E01002886  2012  
4                  E01002890  2012  

[5 rows x 33 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 464697 entries, 0 to 464696
Data columns (total 33 columns):
Accident_Index                                 464697 non-null object
Location_Easting_OSGR                          464697 non-null int64
Location_Northing_OSGR                         464697 non-null int64
Longitude                                      464697 non-null float64
Latitude                                       464697 non-null float64
Police_Force                                   464697 non-null int64
Accident_Severity                              464697 non-null int64
Number_of_Vehicles                             464697 non-null int64
Number_of_Casualties                           464697 non-null int64
Date                                           464697 non-null object
Day_of_Week                                    464697 non-null int64
Time                                           464684 non-null object
Local_Authority_(District)                     464697 

In [29]:
df.describe()

Location_Easting_OSGR  Location_Northing_OSGR      Longitude  \
count          464697.000000            4.646970e+05  464697.000000   
mean           443834.284222            2.986258e+05      -1.375156   
std             94098.865933            1.594701e+05       1.382137   
min             65510.000000            1.029000e+04      -7.509162   
25%            379059.000000            1.777100e+05      -2.315799   
50%            445539.000000            2.606800e+05      -1.323374   
75%            525350.000000            3.989590e+05      -0.192935   
max            655370.000000            1.190858e+06       1.759382   

            Latitude   Police_Force  Accident_Severity  Number_of_Vehicles  \
count  464697.000000  464697.000000      464697.000000       464697.000000   
mean       52.575498      28.504051           2.833461            1.828086   
std         1.436370      25.334899           0.402029            0.708703   
min        49.912941       1.000000           1.000000            1.000000   
25%        51.484841       6.000000           3.000000            1.000000   
50%        52.232169      22.000000           3.000000            2.000000   
75%        53.485973      45.000000           3.000000            2.000000   
max        60.597984      98.000000           3.000000           67.000000   

       Number_of_Casualties    Day_of_Week  Local_Authority_(District)  \
count         464697.000000  464697.000000               464697.000000   
mean               1.334420       4.108740                  329.123829   
std                0.821047       1.916429                  259.222621   
min                1.000000       1.000000                    1.000000   
25%                1.000000       2.000000                   95.000000   
50%                1.000000       4.000000                  300.000000   
75%                1.000000       6.000000                  511.000000   
max               93.000000       7.000000                  941.000000   

       1st_Road_Class  1st_Road_Number    Speed_limit  Junction_Detail  \
count   464697.000000    464697.000000  464697.000000              0.0   
mean         4.070136      1012.728324      38.229793              NaN   
std          1.413850      1810.523701      13.800546              NaN   
min          1.000000         0.000000      10.000000              NaN   
25%          3.000000         0.000000      30.000000              NaN   
50%          3.000000       147.000000      30.000000              NaN   
75%          6.000000       759.000000      40.000000              NaN   
max          6.000000      9999.000000      70.000000              NaN   

       2nd_Road_Class  2nd_Road_Number  Urban_or_Rural_Area           Year  
count   464697.000000    464697.000000        464697.000000  464697.000000  
mean         2.786293       380.952317             1.337426    2012.928140  
std          3.187084      1289.786824             0.472832       0.834536  
min         -1.000000        -1.000000             1.000000    2012.000000  
25%         -1.000000         0.000000             1.000000    2012.000000  
50%          3.000000         0.000000             1.000000    2013.000000  
75%          6.000000         0.000000             2.000000    2014.000000  
max          6.000000      9999.000000             2.000000    2014.000000

### Selecting Features and Cleaning Data

In [3]:
features = pd.DataFrame()

In [4]:
features = df[['Accident_Severity','Number_of_Vehicles','Number_of_Casualties','Day_of_Week','Road_Type','Speed_limit','Light_Conditions','Weather_Conditions','Road_Surface_Conditions','Urban_or_Rural_Area']]

In [5]:
features['mult_casualties'] = np.where(features['Number_of_Casualties'] > 1 , 1, 0)

C:\Users\etallen127\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [6]:
X = features.drop(features[['mult_casualties','Number_of_Casualties']],axis=1)

In [7]:
X = pd.get_dummies(X)

In [8]:
Y = features['mult_casualties']

### Importing Libraries and Setting Up Model

In [9]:
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from matplotlib.mlab import PCA as mlabPCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix

C:\Users\etallen127\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30)

## Decision Tree

Training a Single decision tree.

In [11]:
dtree = DecisionTreeClassifier()

In [12]:
dtree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

## Prediction and Evaluation 

Let's evaluate our decision tree.

In [13]:
predictions = dtree.predict(X_test)

In [14]:
print(classification_report(Y_test,predictions))

             precision    recall  f1-score   support

          0       0.79      0.97      0.87    108367
          1       0.50      0.12      0.19     31043

avg / total       0.73      0.78      0.72    139410



In [15]:
print(confusion_matrix(Y_test,predictions))

[[104595   3772]
 [ 27312   3731]]


In [33]:
cross_val_score(dtree.fit(X_train,Y_train), X,Y, cv=10)

array([ 0.79408663,  0.79068216,  0.77215408,  0.77753389,  0.77751237,
        0.77419841,  0.77804558,  0.78086466,  0.77415051,  0.77466698])

## Analysis for Decision Tree before PCA

Our decision tree is averaging about 77% however it is jumping up and down a little bit, I think we can improve this by reducing the amount of data in our model to do this I will use pricipal component analysis

### Applying pca

In [35]:
# scaling our X training data to prep for pca
ss = StandardScaler().fit_transform(X_train)

In [36]:
# using pca to select 20 components from X's features
sklearn_pca = PCA(n_components=20)

# fitting our x training data to pca
Y_sklearn = sklearn_pca.fit_transform(ss)

# adding results to a new data frame
X_PCA = pd.DataFrame(Y_sklearn)

In [37]:
# using pca to select 10 components from X's features
sklearn_pca2 = PCA(n_components=10)

# fitting our x training data to pca
Y_sklearn2 = sklearn_pca.fit_transform(X_PCA)

# adding results to a new data frame
X_PCA2 = pd.DataFrame(Y_sklearn2)

In [38]:
# using pca to select 5 components from X's features
sklearn_pca3 = PCA(n_components=5)

# fitting our x training data to pca
Y_sklearn3 = sklearn_pca.fit_transform(X_PCA2)

# adding results to a new data frame
X_PCA3 = pd.DataFrame(Y_sklearn3)

In [39]:
# using pca to select 3 components from X's features
sklearn_pca4 = PCA(n_components=3)

# fitting our x training data to pca
Y_sklearn4 = sklearn_pca.fit_transform(X_PCA3)

# adding results to a new data frame
X_PCA4 = pd.DataFrame(Y_sklearn4)

In [40]:
cross_val_score(dtree, X_PCA4, Y_train, cv=10)

array([ 0.77918165,  0.77853608,  0.77687602,  0.7786283 ,  0.77850533,
        0.77755234,  0.77709121,  0.77567709,  0.78065052,  0.77646263])

## Analysis for Decision Tree post PCA

After applying pca our model is much more consistent, its accuracy is still around 77% but there arent any spikes in our test and our predictions were calculated much quicker

## Random Forest Model

In [42]:
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [43]:
rfc_pred = rfc.predict(X_test)

In [45]:
print(confusion_matrix(Y_test,rfc_pred))cross_val_score(dtree.fit(X_train,Y_train), X,Y, cv=10)

[[104470   3897]
 [ 27070   3973]]


In [46]:
print(classification_report(Y_test,rfc_pred))

             precision    recall  f1-score   support

          0       0.79      0.96      0.87    108367
          1       0.50      0.13      0.20     31043

avg / total       0.73      0.78      0.72    139410



In [47]:
cross_val_score(rfc.fit(X_train,Y_train), X,Y, cv=10)

array([ 0.7947322 ,  0.79119862,  0.77224015,  0.77813643,  0.77826555,
        0.77413385,  0.77955196,  0.78200521,  0.7745809 ,  0.77658224])

## Random Forest Analysis before PCA

Our model is a little bit more accurate then our decision tree producing a few 79s and a 78 but over all it really isnt much better and took about 10minutes to compute the results of our cross validation

In [48]:
cross_val_score(rfc.fit(X_PCA4,Y_train), X,Y, cv=10)

array([ 0.79440942,  0.79134926,  0.77146546,  0.77865289,  0.77815795,
        0.77503766,  0.77918612,  0.78189761,  0.7747961 ,  0.77615184])

## Random Forest Analysis After PCA

Our model didn't really improve much from PCA its scores were almost Identical to the first test. This could be do to the fact that this model already ran 100 instances of our first model.  Overall I would say that the slight increase in accuracy would not be worth it with this type of data.  A much larger dataset would just take a lot longer to work with, without returning much benefit for our model.

## Comparison of Decision Tree and Random Forest

The random forest model is able to average a higher accuracy rate but it comes at the cost of time.  The single decision tree was only a couple of percentile behind the random forests model and took a fraction of the time to compute.  Using cross validation and PCA both models were very consistent after 10 tests.  Another benefit to our single decision tree is the power to map it out using pydot and graphviz. I had a problem on my local enviornment with graphviz, but normally a single decision tree is less of a black box then our random forest model.